### ISSUE TITLE
Small documentation improvements

### ISSUE THREAD

**Issue by phofl** [noatamir/pyladies-workshop#6]
- [ ] Replace all occurrences of external functions with correct links to their respective documentation (see https://github.com/pandas-dev/pandas/pull/49709/files for a pyarrow example) -> requires finding the occurrences yourselves. 
- [ ] Update documentation for str.cat: https://github.com/pandas-dev/pandas/issues/35556. There was a PR, but it was closed: https://github.com/pandas-dev/pandas/pull/35784
- [ ] Add an example to https://pandas.pydata.org/docs/reference/api/pandas.read_parquet.html, https://github.com/pandas-dev/pandas/issues/49739
- [x] https://github.com/pandas-dev/pandas/issues/52238
- [x] https://github.com/pandas-dev/pandas/issues/51420 (needs either knowledge about value_counts or testing the described cases)
- [x] https://github.com/pandas-dev/pandas/issues/50496
- [x] https://github.com/pandas-dev/pandas/issues/47529
- [x] https://github.com/pandas-dev/pandas/issues/46440
- [x] https://github.com/pandas-dev/pandas/issues/44945
- [ ] https://github.com/pandas-dev/pandas/issues/38437 (document limitation)
- [x] https://github.com/pandas-dev/pandas/issues/35206
- [x] https://github.com/pandas-dev/pandas/issues/52716

**Comment by maanijou** [comment]
took this with @gmollard

**Comment by chennnxu** [comment]
take DOC: Example missing in pandas.DataFrame.to_html #44945

**Comment by MirijaH** [comment]
take DOC: Document the filters argument in read_parquet #52238
